export type HadoSeoStatus =
  | "✅ OPTIMISÉ"
  | "✅ OK"
  | "✅ DYNAMIQUE";

export type HadoSeoMetadataOverride = {
  route: string;
  title: string;
  description: string;
  canonical: string;
  ogImage: string;
  status: HadoSeoStatus;
};

export const hadoseoMetadataOverrides: HadoSeoMetadataOverride[] = [
  {
    route: "/",
    title: "Agence de prospection B2B en Suisse | RDV qualifiés | devlo",
    description: "devlo genere des rendez-vous qualifies en Suisse via lead generation, cold email, LinkedIn et calling. Campagnes multilingues et preuves clients.",
    canonical: "https://devlo.ch/",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/academy",
    title: "Outbound Academy | Formation prospection B2B | devlo",
    description: "Formation prospection B2B avec 50 tutoriels vidéo: cold email LinkedIn téléprospection et génération de leads. Méthodologie complète accès à vie.",
    canonical: "https://devlo.ch/academy",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/consultation",
    title: "Consultation gratuite | Audit lead generation B2B | devlo",
    description: "Auditez votre potentiel de leads qualifiés : ICP TAM signaux d'achat séquences et plan d'action pour générer des rendez-vous B2B.",
    canonical: "https://devlo.ch/consultation",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/conditions",
    title: "Conditions générales d'utilisation | devlo",
    description: "Consultez les conditions générales d'utilisation de devlo.ch: licence responsabilité propriété intellectuelle et droit applicable.",
    canonical: "https://devlo.ch/conditions",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OK",
  },
  {
    route: "/etudes-de-cas",
    title: "Études de cas | Résultats prospection B2B | devlo",
    description: "Découvrez les résultats concrets de nos campagnes B2B: taux d'ouverture taux de réponse et rendez-vous qualifiés obtenus sur des cas clients réels.",
    canonical: "https://devlo.ch/etudes-de-cas",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services",
    title: "Services prospection B2B | Cold email, LinkedIn, Téléprospection | devlo",
    description: "10 services de prospection B2B externalisés : cold email, LinkedIn outreach, cold calling, génération de leads, enrichissement Clay et intent data. Basé en Suisse.",
    canonical: "https://devlo.ch/services",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/outbound-multicanal",
    title: "Outbound Multicanal B2B | Cold email + LinkedIn + Calling | devlo",
    description: "Agence outbound multicanal B2B en Suisse : cold email LinkedIn et calling coordonnés pour générer des rendez-vous qualifiés avec les bons décideurs.",
    canonical: "https://devlo.ch/services/outbound-multicanal",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/cold-email",
    title: "Cold Email B2B | Infrastructure & campagnes multicanales | devlo",
    description: "Agence cold email B2B en Suisse : infrastructure délivrabilité, séquences personnalisées et A/B testing. +50% de taux d'ouverture vs la moyenne du marché.",
    canonical: "https://devlo.ch/services/cold-email",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/linkedin-outreach",
    title: "LinkedIn Outreach B2B | Prospection LinkedIn Suisse | devlo",
    description: "Agence LinkedIn outreach B2B en Suisse : ciblage Sales Navigator, messages ultra-personnalisés, séquences multicanales. Taux de réponse moyen 8-12%.",
    canonical: "https://devlo.ch/services/linkedin-outreach",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/cold-calling",
    title: "Cold Calling B2B | Téléprospection Suisse FR/DE/EN | devlo",
    description: "Téléprospection B2B externalisée en Suisse : équipe native FR/DE/EN, qualification téléphonique et prise de rendez-vous qualifiés. Résultats dès J+15.",
    canonical: "https://devlo.ch/services/cold-calling",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/intent-data",
    title: "Intent Data B2B | Signaux | devlo",
    description: "Activation de signaux d'intention B2B : levées de fonds recrutements migrations technologiques signaux G2 et intent data multi-sources.",
    canonical: "https://devlo.ch/services/intent-data",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/enrichissement-clay",
    title: "Enrichissement Clay B2B | devlo",
    description: "Agence Clay B2B : enrichissement de prospects via Clay Apollo ZoomInfo Cognism et Crunchbase pour des listes fiables et actionnables.",
    canonical: "https://devlo.ch/services/enrichissement-clay",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/generation-leads",
    title: "Lead Generation B2B Suisse | Listes ICP qualifiées | devlo",
    description: "Agence lead generation B2B en Suisse : ICP TAM signaux d'achat décideurs emails vérifiés et scoring pour séquences outbound.",
    canonical: "https://devlo.ch/services/generation-leads",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/qualification-leads",
    title: "Qualification leads B2B | SDR | devlo",
    description: "Service SDR externalisé B2B : qualification des leads entrants/sortants discovery calls et planification de démos qualifiées.",
    canonical: "https://devlo.ch/services/qualification-leads",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/prise-de-rendez-vous",
    title: "Prise de RDV B2B | Booking | devlo",
    description: "Service de prise de rendez-vous B2B externalisé : gestion inbox qualification booking agenda et réduction du no-show.",
    canonical: "https://devlo.ch/services/prise-de-rendez-vous",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/services/crm-delivrabilite",
    title: "CRM & Délivrabilité B2B | devlo",
    description: "Setup CRM et infrastructure email B2B : HubSpot/Salesforce SPF-DKIM-DMARC domaines secondaires warm-up et monitoring délivrabilité.",
    canonical: "https://devlo.ch/services/crm-delivrabilite",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/etudes-de-cas/logiciel-comptable-200k-ca",
    title: "Étude de cas Horus | Prospection B2B | devlo",
    description: "Découvrez comment ce logiciel de comptabilité a obtenu €200K de nouveaux contrats via 80 rendez-vous qualifiés avec des cabinets comptables.",
    canonical: "https://devlo.ch/etudes-de-cas/logiciel-comptable-200k-ca",
    ogImage: "/images/Horus.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/hr-54-rendez-vous-dach",
    title: "Étude de cas CareerLunch | Prospection B2B | devlo",
    description: "CareerLunch plateforme HR-tech souhaitait accélérer sa prospection commerciale dans la région DACH (Allemagne Autriche Suisse) sans surcharger son équipe...",
    canonical: "https://devlo.ch/etudes-de-cas/hr-54-rendez-vous-dach",
    ogImage: "/images/CareerLunch_banner1.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/proprete-urbaine-71-rendez-vous",
    title: "Étude de cas Client confidentiel | Prospection B2B | devlo",
    description: "Agence de Prospection Commerciale et de Génération de prospects B2B: Comment cette entreprise a obtenu 71 rendez-vous qualifiés avec des villes d'Europe.",
    canonical: "https://devlo.ch/etudes-de-cas/proprete-urbaine-71-rendez-vous",
    ogImage: "/images/Cortexia_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/biocarburants-52-rendez-vous",
    title: "Étude de cas Square Co | Prospection B2B | devlo",
    description: "Campagnes de prospection B2B (multicanales & personnalisées): Comment identifier les meilleurs prospects parmi plusieurs ICP via notre méthodologie.",
    canonical: "https://devlo.ch/etudes-de-cas/biocarburants-52-rendez-vous",
    ogImage: "/images/SquareCo_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/formation-14-rendez-vous",
    title: "Étude de cas Cegos | Prospection B2B | devlo",
    description: "Découvrez comment nous avons pris des rendez-vous qualifiés avec des décideurs suisses en matière de R&D et comment nous avons obtenu un taux de réponse impr...",
    canonical: "https://devlo.ch/etudes-de-cas/formation-14-rendez-vous",
    ogImage: "/images/Cegos_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/audiovisuel-16-rendez-vous",
    title: "Étude de cas Lemanvisio | Prospection B2B | devlo",
    description: "Découvrez la séquence multicanal lemlist de cet intégrateur audiovisuel. Génération de prospects et rendez-vous qualifiés par notre Agence de Prospection B2B.",
    canonical: "https://devlo.ch/etudes-de-cas/audiovisuel-16-rendez-vous",
    ogImage: "/images/LEMANVISIO_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/cybersecurite-4500-entreprises",
    title: "Étude de cas Saporo | Prospection B2B | devlo",
    description: "Saporo éditeur de solution de cybersécurité voulait valider son product-market fit sur plusieurs cibles et externaliser sa prospection commerciale B2B pour...",
    canonical: "https://devlo.ch/etudes-de-cas/cybersecurite-4500-entreprises",
    ogImage: "/images/Saporo_Banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/biodiversite-70-rendez-vous",
    title: "Étude de cas Apidae | Prospection B2B | devlo",
    description: "Agence de prospection: Comment cette entreprise B2B a externalisé son acquisition clients et obtenu 70 rendez-vous qualifiés avec des décideurs.",
    canonical: "https://devlo.ch/etudes-de-cas/biodiversite-70-rendez-vous",
    ogImage: "/images/APIDAE_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/mobilite-40-prospects",
    title: "Étude de cas Locky | Prospection B2B | devlo",
    description: "Agence de Prospection Commerciale B2B: comment ce client a rencontré +40 prospects qualifiés (séquences d'e-mails appels démarchage LinkedIn)",
    canonical: "https://devlo.ch/etudes-de-cas/mobilite-40-prospects",
    ogImage: "/images/Locky_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/merchandising-23-prospects",
    title: "Étude de cas Many Ways | Prospection B2B | devlo",
    description: "Comment cette société de merchandising a obtenu 70% de réponses et 8% de meetings avec leurs prospects grâce à cette séquence de prospection commerciale B2B",
    canonical: "https://devlo.ch/etudes-de-cas/merchandising-23-prospects",
    ogImage: "/images/Many-Ways_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/immobilier-11-prospects",
    title: "Étude de cas HIAG | Prospection B2B | devlo",
    description: "L'immobilier et la prospection commerciale B2B: comment cibler et démarcher des prospects pour la location de surfaces commerciales",
    canonical: "https://devlo.ch/etudes-de-cas/immobilier-11-prospects",
    ogImage: "/images/HIAG_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/immobilier-30-prospects",
    title: "Étude de cas Abacus | Prospection B2B | devlo",
    description: "Découvrez comment Abacus a utilisé la télémarketing B2B et la génération de leads pour rencontrer des agences immobilières qualifiées en Suisse romande.",
    canonical: "https://devlo.ch/etudes-de-cas/immobilier-30-prospects",
    ogImage: "/images/Abacus_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/monizze-120-rendez-vous",
    title: "Étude de cas Monizze | Prospection B2B | devlo",
    description: "Comment devlo a obtenu 120 rendez-vous qualifiés pour Monizze en ciblant 7'000 décideurs RH Finance et Direction en Belgique.",
    canonical: "https://devlo.ch/etudes-de-cas/monizze-120-rendez-vous",
    ogImage: "/images/Monizze_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/etudes-de-cas/iddi-generation-leads-biotech-pharma",
    title: "Étude de cas IDDI | Prospection B2B | devlo",
    description: "IDDI CRO spécialisé en biostatistique et gestion des données cliniques génère des rendez-vous qualifiés auprès de décideurs biotech et pharma.",
    canonical: "https://devlo.ch/etudes-de-cas/iddi-generation-leads-biotech-pharma",
    ogImage: "/images/IDDI_banner.webp",
    status: "✅ DYNAMIQUE",
  },
  {
    route: "/agence",
    title: "À propos de devlo | Agence B2B Suisse depuis 2020 | devlo",
    description: "devlo, agence de prospection B2B fondée en Suisse en 2020. +1000 campagnes, 4.9/5, 4 marchés (CH, BE, FR, DE). Découvrez notre équipe et notre mission.",
    canonical: "https://devlo.ch/agence",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/prospection-commerciale-suisse",
    title: "Prospection B2B Suisse | Leads qualifiés et RDV | devlo",
    description: "Agence B2B basée en Suisse pour lead generation séquences outbound et rendez-vous qualifiés en Romandie Suisse alémanique et Tessin.",
    canonical: "https://devlo.ch/prospection-commerciale-suisse",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/prospection-commerciale-belgique",
    title: "Prospection commerciale Belgique | Agence B2B FR/NL | devlo",
    description: "Agence de prospection B2B en Belgique. Campagnes cold email, LinkedIn et calling en français et néerlandais. Résultats mesurables dès la 3e semaine.",
    canonical: "https://devlo.ch/prospection-commerciale-belgique",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
  {
    route: "/prospection-commerciale-france",
    title: "Prospection commerciale France | Agence B2B externalisée | devlo",
    description: "Agence de prospection B2B en France. Cold email, LinkedIn outreach et téléprospection externalisés. Équipe francophone, +50 clients français accompagnés.",
    canonical: "https://devlo.ch/prospection-commerciale-france",
    ogImage: "/images/devlo_OG_Banner.webp",
    status: "✅ OPTIMISÉ",
  },
];

export const hadoseoMetadataByRoute = Object.freeze(
  Object.fromEntries(hadoseoMetadataOverrides.map((item) => [item.route, item])) as Record<string, HadoSeoMetadataOverride>,
);
